### ISSUE TITLE
pthread not linked in

### ISSUE THREAD

**Issue by fmeum** [orycho/Intro#4]
When building the tests on a UNIX-based system via `make test`, the following error message is shown:

`/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line`

gtest requires pthread to get linked in, which can be accomplished by adding `-lpthread` at the end of the command for the target `test_$(BIN)`.

**Comment by orycho** [comment]
Thanks for the report, funny how that worked in cygwin. Maybe gtest got compiled differently in my environment. Added it anyway as it does not hurt my build.
